services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: torneo_piston
    restart: unless-stopped
    privileged: true
    environment:
      - PISTON_RUN_TIMEOUT=5000
    ports:
      - '2000:2000'
    volumes:
      - ./piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec
