/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTorneoRouteImport } from './routes/admin/torneo'
import { Route as AdminParticipantesRouteImport } from './routes/admin/participantes'
import { Route as AdminIngresoRouteImport } from './routes/admin/ingreso'
import { Route as AdminAdministradoresRouteImport } from './routes/admin/administradores'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppClasificacionRouteImport } from './routes/_app/clasificacion'
import { Route as AdminProblemasIndexRouteImport } from './routes/admin/problemas/index'
import { Route as AdminEnviosIndexRouteImport } from './routes/admin/envios/index'
import { Route as AppProblemasIndexRouteImport } from './routes/_app/problemas/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProblemasProblemaIdRouteImport } from './routes/admin/problemas/$problemaId'
import { Route as AdminEnviosEnvioIdRouteImport } from './routes/admin/envios/$envioId'
import { Route as AppProblemasProblemaIdRouteImport } from './routes/_app/problemas/$problemaId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTorneoRoute = AdminTorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParticipantesRoute = AdminParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIngresoRoute = AdminIngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClasificacionRoute = AppClasificacionRouteImport.update({
  id: '/clasificacion',
  path: '/clasificacion',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminProblemasIndexRoute = AdminProblemasIndexRouteImport.update({
  id: '/problemas/',
  path: '/problemas/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnviosIndexRoute = AdminEnviosIndexRouteImport.update({
  id: '/envios/',
  path: '/envios/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppProblemasIndexRoute = AppProblemasIndexRouteImport.update({
  id: '/problemas/',
  path: '/problemas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemasProblemaIdRoute =
  AdminProblemasProblemaIdRouteImport.update({
    id: '/problemas/$problemaId',
    path: '/problemas/$problemaId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEnviosEnvioIdRoute = AdminEnviosEnvioIdRouteImport.update({
  id: '/envios/$envioId',
  path: '/envios/$envioId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppProblemasProblemaIdRoute = AppProblemasProblemaIdRouteImport.update({
  id: '/problemas/$problemaId',
  path: '/problemas/$problemaId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/clasificacion': typeof AppClasificacionRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/problemas/$problemaId': typeof AppProblemasProblemaIdRoute
  '/admin/envios/$envioId': typeof AdminEnviosEnvioIdRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/problemas/': typeof AppProblemasIndexRoute
  '/admin/envios/': typeof AdminEnviosIndexRoute
  '/admin/problemas/': typeof AdminProblemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/clasificacion': typeof AppClasificacionRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/problemas/$problemaId': typeof AppProblemasProblemaIdRoute
  '/admin/envios/$envioId': typeof AdminEnviosEnvioIdRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/problemas': typeof AppProblemasIndexRoute
  '/admin/envios': typeof AdminEnviosIndexRoute
  '/admin/problemas': typeof AdminProblemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app/clasificacion': typeof AppClasificacionRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/_app/problemas/$problemaId': typeof AppProblemasProblemaIdRoute
  '/admin/envios/$envioId': typeof AdminEnviosEnvioIdRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/problemas/': typeof AppProblemasIndexRoute
  '/admin/envios/': typeof AdminEnviosIndexRoute
  '/admin/problemas/': typeof AdminProblemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clasificacion'
    | '/perfil'
    | '/admin/administradores'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/problemas/$problemaId'
    | '/admin/envios/$envioId'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/problemas/'
    | '/admin/envios/'
    | '/admin/problemas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clasificacion'
    | '/perfil'
    | '/admin/administradores'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/problemas/$problemaId'
    | '/admin/envios/$envioId'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/problemas'
    | '/admin/envios'
    | '/admin/problemas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/_app/clasificacion'
    | '/_app/perfil'
    | '/admin/administradores'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/_app/problemas/$problemaId'
    | '/admin/envios/$envioId'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/_app/problemas/'
    | '/admin/envios/'
    | '/admin/problemas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/torneo': {
      id: '/admin/torneo'
      path: '/torneo'
      fullPath: '/admin/torneo'
      preLoaderRoute: typeof AdminTorneoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/participantes': {
      id: '/admin/participantes'
      path: '/participantes'
      fullPath: '/admin/participantes'
      preLoaderRoute: typeof AdminParticipantesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ingreso': {
      id: '/admin/ingreso'
      path: '/ingreso'
      fullPath: '/admin/ingreso'
      preLoaderRoute: typeof AdminIngresoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clasificacion': {
      id: '/_app/clasificacion'
      path: '/clasificacion'
      fullPath: '/clasificacion'
      preLoaderRoute: typeof AppClasificacionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/problemas/': {
      id: '/admin/problemas/'
      path: '/problemas'
      fullPath: '/admin/problemas/'
      preLoaderRoute: typeof AdminProblemasIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/envios/': {
      id: '/admin/envios/'
      path: '/envios'
      fullPath: '/admin/envios/'
      preLoaderRoute: typeof AdminEnviosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/problemas/': {
      id: '/_app/problemas/'
      path: '/problemas'
      fullPath: '/problemas/'
      preLoaderRoute: typeof AppProblemasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problemas/$problemaId': {
      id: '/admin/problemas/$problemaId'
      path: '/problemas/$problemaId'
      fullPath: '/admin/problemas/$problemaId'
      preLoaderRoute: typeof AdminProblemasProblemaIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/envios/$envioId': {
      id: '/admin/envios/$envioId'
      path: '/envios/$envioId'
      fullPath: '/admin/envios/$envioId'
      preLoaderRoute: typeof AdminEnviosEnvioIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/problemas/$problemaId': {
      id: '/_app/problemas/$problemaId'
      path: '/problemas/$problemaId'
      fullPath: '/problemas/$problemaId'
      preLoaderRoute: typeof AppProblemasProblemaIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppClasificacionRoute: typeof AppClasificacionRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProblemasProblemaIdRoute: typeof AppProblemasProblemaIdRoute
  AppProblemasIndexRoute: typeof AppProblemasIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClasificacionRoute: AppClasificacionRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProblemasProblemaIdRoute: AppProblemasProblemaIdRoute,
  AppProblemasIndexRoute: AppProblemasIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminIngresoRoute: typeof AdminIngresoRoute
  AdminParticipantesRoute: typeof AdminParticipantesRoute
  AdminTorneoRoute: typeof AdminTorneoRoute
  AdminEnviosEnvioIdRoute: typeof AdminEnviosEnvioIdRoute
  AdminProblemasProblemaIdRoute: typeof AdminProblemasProblemaIdRoute
  AdminEnviosIndexRoute: typeof AdminEnviosIndexRoute
  AdminProblemasIndexRoute: typeof AdminProblemasIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminIngresoRoute: AdminIngresoRoute,
  AdminParticipantesRoute: AdminParticipantesRoute,
  AdminTorneoRoute: AdminTorneoRoute,
  AdminEnviosEnvioIdRoute: AdminEnviosEnvioIdRoute,
  AdminProblemasProblemaIdRoute: AdminProblemasProblemaIdRoute,
  AdminEnviosIndexRoute: AdminEnviosIndexRoute,
  AdminProblemasIndexRoute: AdminProblemasIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
