/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ClasificacionRouteImport } from './routes/clasificacion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemasIndexRouteImport } from './routes/problemas/index'
import { Route as ProblemasProblemaIdRouteImport } from './routes/problemas/$problemaId'
import { Route as AdminTorneoRouteImport } from './routes/admin/torneo'
import { Route as AdminParticipantesRouteImport } from './routes/admin/participantes'
import { Route as AdminIngresoRouteImport } from './routes/admin/ingreso'
import { Route as AdminEnviosRouteImport } from './routes/admin/envios'
import { Route as AdminAdministradoresRouteImport } from './routes/admin/administradores'
import { Route as AdminProblemasIndexRouteImport } from './routes/admin/problemas/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProblemasProblemaIdRouteImport } from './routes/admin/problemas/$problemaId'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasificacionRoute = ClasificacionRouteImport.update({
  id: '/clasificacion',
  path: '/clasificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemasIndexRoute = ProblemasIndexRouteImport.update({
  id: '/problemas/',
  path: '/problemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemasProblemaIdRoute = ProblemasProblemaIdRouteImport.update({
  id: '/problemas/$problemaId',
  path: '/problemas/$problemaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTorneoRoute = AdminTorneoRouteImport.update({
  id: '/admin/torneo',
  path: '/admin/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantesRoute = AdminParticipantesRouteImport.update({
  id: '/admin/participantes',
  path: '/admin/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngresoRoute = AdminIngresoRouteImport.update({
  id: '/admin/ingreso',
  path: '/admin/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnviosRoute = AdminEnviosRouteImport.update({
  id: '/admin/envios',
  path: '/admin/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/admin/administradores',
  path: '/admin/administradores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemasIndexRoute = AdminProblemasIndexRouteImport.update({
  id: '/admin/problemas/',
  path: '/admin/problemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemasProblemaIdRoute =
  AdminProblemasProblemaIdRouteImport.update({
    id: '/admin/problemas/$problemaId',
    path: '/admin/problemas/$problemaId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clasificacion': typeof ClasificacionRoute
  '/perfil': typeof PerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/envios': typeof AdminEnviosRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/problemas/$problemaId': typeof ProblemasProblemaIdRoute
  '/problemas/': typeof ProblemasIndexRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/problemas/': typeof AdminProblemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clasificacion': typeof ClasificacionRoute
  '/perfil': typeof PerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/envios': typeof AdminEnviosRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/problemas/$problemaId': typeof ProblemasProblemaIdRoute
  '/problemas': typeof ProblemasIndexRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/problemas': typeof AdminProblemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clasificacion': typeof ClasificacionRoute
  '/perfil': typeof PerfilRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/envios': typeof AdminEnviosRoute
  '/admin/ingreso': typeof AdminIngresoRoute
  '/admin/participantes': typeof AdminParticipantesRoute
  '/admin/torneo': typeof AdminTorneoRoute
  '/problemas/$problemaId': typeof ProblemasProblemaIdRoute
  '/problemas/': typeof ProblemasIndexRoute
  '/admin/problemas/$problemaId': typeof AdminProblemasProblemaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/problemas/': typeof AdminProblemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clasificacion'
    | '/perfil'
    | '/admin/administradores'
    | '/admin/envios'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/problemas/$problemaId'
    | '/problemas/'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/admin/problemas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clasificacion'
    | '/perfil'
    | '/admin/administradores'
    | '/admin/envios'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/problemas/$problemaId'
    | '/problemas'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/admin/problemas'
  id:
    | '__root__'
    | '/'
    | '/clasificacion'
    | '/perfil'
    | '/admin/administradores'
    | '/admin/envios'
    | '/admin/ingreso'
    | '/admin/participantes'
    | '/admin/torneo'
    | '/problemas/$problemaId'
    | '/problemas/'
    | '/admin/problemas/$problemaId'
    | '/api/auth/$'
    | '/admin/problemas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClasificacionRoute: typeof ClasificacionRoute
  PerfilRoute: typeof PerfilRoute
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminEnviosRoute: typeof AdminEnviosRoute
  AdminIngresoRoute: typeof AdminIngresoRoute
  AdminParticipantesRoute: typeof AdminParticipantesRoute
  AdminTorneoRoute: typeof AdminTorneoRoute
  ProblemasProblemaIdRoute: typeof ProblemasProblemaIdRoute
  ProblemasIndexRoute: typeof ProblemasIndexRoute
  AdminProblemasProblemaIdRoute: typeof AdminProblemasProblemaIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AdminProblemasIndexRoute: typeof AdminProblemasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasificacion': {
      id: '/clasificacion'
      path: '/clasificacion'
      fullPath: '/clasificacion'
      preLoaderRoute: typeof ClasificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemas/': {
      id: '/problemas/'
      path: '/problemas'
      fullPath: '/problemas/'
      preLoaderRoute: typeof ProblemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemas/$problemaId': {
      id: '/problemas/$problemaId'
      path: '/problemas/$problemaId'
      fullPath: '/problemas/$problemaId'
      preLoaderRoute: typeof ProblemasProblemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/torneo': {
      id: '/admin/torneo'
      path: '/admin/torneo'
      fullPath: '/admin/torneo'
      preLoaderRoute: typeof AdminTorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participantes': {
      id: '/admin/participantes'
      path: '/admin/participantes'
      fullPath: '/admin/participantes'
      preLoaderRoute: typeof AdminParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingreso': {
      id: '/admin/ingreso'
      path: '/admin/ingreso'
      fullPath: '/admin/ingreso'
      preLoaderRoute: typeof AdminIngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/envios': {
      id: '/admin/envios'
      path: '/admin/envios'
      fullPath: '/admin/envios'
      preLoaderRoute: typeof AdminEnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/admin/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problemas/': {
      id: '/admin/problemas/'
      path: '/admin/problemas'
      fullPath: '/admin/problemas/'
      preLoaderRoute: typeof AdminProblemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problemas/$problemaId': {
      id: '/admin/problemas/$problemaId'
      path: '/admin/problemas/$problemaId'
      fullPath: '/admin/problemas/$problemaId'
      preLoaderRoute: typeof AdminProblemasProblemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClasificacionRoute: ClasificacionRoute,
  PerfilRoute: PerfilRoute,
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminEnviosRoute: AdminEnviosRoute,
  AdminIngresoRoute: AdminIngresoRoute,
  AdminParticipantesRoute: AdminParticipantesRoute,
  AdminTorneoRoute: AdminTorneoRoute,
  ProblemasProblemaIdRoute: ProblemasProblemaIdRoute,
  ProblemasIndexRoute: ProblemasIndexRoute,
  AdminProblemasProblemaIdRoute: AdminProblemasProblemaIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AdminProblemasIndexRoute: AdminProblemasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
